apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: toci510nx-go
  janus-idp.io/tekton: toci510nx-go
  backstage.io/kubernetes-id: toci510nx-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: toci510nx-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
